### ISSUE TITLE
关于网站登录不了

### ISSUE THREAD

**Issue by shuncon** [xsec-lab/x-waf-admin#2]
[database]
USER = wafadmin
PASSWD = shunconf12
HOST =127.0.0.1:3306
NAME = waf
在app.ini设置了和没设置都登录不了
也是用文档中的admin和x@xsec.io的口令密码都不行，要么弹出验证码，要么就提示无效的令牌，还有就是刷新网页

**Comment by trockxi** [comment]
在数据库里先新建一个waf的数据库，然后重启x-waf的server服务再登录试试

**Comment by netxfly** [comment]
确认下数据库是否正常连接。
