### ISSUE TITLE
server启动没有新建用户，登录失败

### ISSUE THREAD

**Issue by py0ker** [xsec-lab/x-waf-admin#4]
您好，麻烦问一下，我已经在数据库中新建账户 waf-admin，密码为passw0rd，而且看这个提示应该是成功连接数据库了，但是没能找到waf数据库中的user表。不知道是哪里的问题呢？下面是报错信息，以及我的配置文件
![tim 20180424112328](https://user-images.githubusercontent.com/29670349/39164400-f01798ae-47b1-11e8-8c4d-1e8946207e03.png)
![tim 20180424112548](https://user-images.githubusercontent.com/29670349/39164483-3f8d4500-47b2-11e8-8ea5-bac529c12878.png)

**Comment by netxfly** [comment]
创建完用户有没有`flush privileges;`？手工用mysql客户端试试那个账户能登录吗？

**Comment by py0ker** [comment]
我刚刚flush privileges; 了，但还是没有成功。手工mysql -u waf-admin -p 是成功登陆的。我试了两种情况，如果我自己在mysql建一个waf数据库，登陆报错waf.user 不存在；如果我把这个数据库删掉，会提示Unknow database 'waf'。不知道这是什么情况呢

**Comment by netxfly** [comment]
mysql测试连接的时候带上-h 参数，配置的时候，host配成-h测试正常的那个地址。localhost与127.0.0.1对mysql来说是2个不错的地址。
